[[redirects]]
  from = "https://www.nandi.tech/*"
  to = "https://nandi.tech/:splat"
  force = true

[[redirects]]
  from = "https://mta-sts.nandi.tech/.well-known/mta-sts.txt"
  to = "https://mta-sts.nandi.tech/.well-known/mta-sts.txt"

[[redirects]]
  from = "https://mta-sts.nandi.tech/*"
  to = "https://nandi.tech/:splat"
  force = true

[[redirects]]
  from = "https://nandi.tech/.well-known/mta-sts.txt"
  to = "https://mta-sts.nandi.tech/.well-known/mta-sts.txt"
  force = true

[[redirects]]
  from = "https://nandi.tech/discord"
  to = "https://discord.gg/QX6BkkFnwv"

[[redirects]]
  from = "https://nandi-tech.netlify.app/*"
  to = "https://nandi.tech/:splat"
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = '''
      max-age=31536000;
      includeSubDomains;
      preload'''
    X-Content-Type-Options = "nosniff"
